# Theme settings
remote_theme: just-the-docs/just-the-docs

# Book settings
title: "APEX Stats"
author: "David Schuster"
logo: "logo.png"

# GitHub Pages URL settings
url: "https://michellebacareinke.github.io"
baseurl: "/apex_stats_book"  # Repository name

# Markdown processing
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Enable Jekyll for GitHub Pages
lsi: false
safe: true
source: .  # Root directory
incremental: false
highlighter: rouge
gist:
  noscript: false

# Just the Docs settings
search_enabled: true  # Enable built-in search
aux_links:
  "APEX Stats Repository":
    - "https://github.com/michellebacareinke/apex_stats_book"

# Navigation settings
nav_order: 1  # Control sidebar page order
nav_sort: case_insensitive  # Optional: Sort navigation item alphabetically
