# Theme settings
theme: jekyll-theme-cayman

# Book settings
title: APEX Stats
author: David Schuster
logo: logo.png

# GitHub Pages URL settings
url: "https://michellebacareinke.github.io"
baseurl: "/APEX_stats_book"  # Repository name

# Markdown processing 
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Enable Jekyll for GitHub Pages
lsi: false
safe: true
source: .  # Root directory
incremental: false
highlighter: rouge
gist:
  noscript: false

# GitHub buttons for issues and repository
html:
  use_issues_button: true
  use_repository_button: true
