# Theme settings
remote_theme: just-the-docs/just-the-docs

# Book settings
title: "APEX Stats"
author: "David Schuster"
logo: "logo.png"

# GitHub Pages URL settings
url: "https://michellebacareinke.github.io"
baseurl: "/apex_stats_book"  # Repository name

permalink: pretty

# Code copy
enable_copy_code_button: true

# Enable heading anchors
heading_anchors: true

# Markdown processing
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Enable Jekyll for GitHub Pages
lsi: false
safe: true
source: .  # Root directory
incremental: false
highlighter: rouge
gist:
  noscript: false

# Just the Docs settings
search_enabled: true  # Enable built-in search
# Enable search button
  button: true
# Focus search input (`ctrl + focus_shortcut_key`(or `cmd + focus_shortcut_key` on macOS)
focus_shortcut_key: "k"
aux_links:
  "APEX Stats Repository":
    - "https://github.com/michellebacareinke/apex_stats_book"

# Navigation settings
nav_order: 1  # Control sidebar page order
nav_sort: case_insensitive  # Optional: Sort navigation item alphabetically

# Enable right-hand TOC sidebar for each page
toc: true
toc_label: "On this page"
toc_sticky: true  # Sticks TOC while scrolling

# Footer content
footer_content: "Copyright © 2024 David Schuster."

# Back-to-top button
back_to_top: true
back_to_top_text: "Back to top"
